spec:
  queueManager:
    availability:
      tls:
        secretName: mq02ha-qm-tls
      nativeHAGroups:
        local:
          name: live_group
          role: Live
          route:
            enabled: true
        remotes:
          - addresses:
              - 'occmq-mq02ha-ibm-mq-nhacrr-occmq.apps.itz-axjnea.infra01-lb.fra02.techzone.ibm.com:443'
            name: recovery_group
            trust:
              - secret:
                  items:
                    - tls.crt
                  secretName: mq02ha-qm-tls
